## put your development specific values in this file

spring:
  rabbitmq:
      addresses: yourRabbitMqServer
      username: guest
      password: guest
      virtual-host: dev

gitHub:
  login: "yourLogin"
  password: "yourPassword"

server:
  port: 8081