apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: grafana
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          name: grafana
      spec:
        containers:
        - image: enmasseproject/grafana:latest
          name: grafana
          ports:
          - containerPort: 3000
            name: grafana
          volumeMounts:
          - mountPath: /usr/share/grafana/data
            name: grafana-data
            readOnly: false
        volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data
- apiVersion: v1
  kind: Service
  metadata:
    name: grafana
  spec:
    ports:
    - name: grafana
      port: 3000
      targetPort: 3000
    selector:
      name: grafana
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: grafana-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
kind: List
