apiVersion: v1
items:
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: enmasse-address-admin
  rules:
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - create
    - delete
    - list
    - get
    - watch
    - update
    - patch
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: enmasse-namespace-admin
  rules:
  - apiGroups:
    - ''
    - user.openshift.io
    resources:
    - users
    verbs:
    - impersonate
  - apiGroups:
    - ''
    - extensions
    - authorization.openshift.io
    - route.openshift.io
    resources:
    - clusterrolebindings
    - rolebindings
    - events
    - policybindings
    - deployments
    - pods
    - configmaps
    - routes
    - serviceaccounts
    - secrets
    - services
    - persistentvolumeclaims
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - rbac.authorization.k8s.io
    resources:
    - clusterrolebindings
    - rolebindings
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - authentication.k8s.io
    resources:
    - tokenreviews
    verbs:
    - create
  - apiGroups:
    - ''
    resources:
    - namespaces
    verbs:
    - get
    - list
    - watch
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: event-reporter
  rules:
  - apiGroups:
    - ''
    resources:
    - events
    verbs:
    - create
    - get
    - update
    - patch
kind: List
