docker:
  image: yegor256/java8
  as_root: true
decrypt:
  settings.xml: "repo/.rultor/settings.xml.asc"
  pubring.gpg: "repo/.rultor/pubring.gpg.asc"
  secring.gpg: "repo/.rultor/secring.gpg.asc"
env:
  MAVEN_OPTS: -Xmx1g
  JAVA_OPTS: -Xmx1g
install: |
  sudo gem install --no-rdoc --no-ri pdd
  sudo gem install --no-rdoc --no-ri xcop
architect:
  - smallcreep
merge:
  script: |
    pdd --file=/dev/null
    mvn clean install -Pqulice -Pintegration -Pcucumber --errors --settings ../settings.xml
deploy:
  script: |
    mvn clean deploy -Pqulice -Pintegration -Pcucumber --errors --settings ../settings.xml
release:
  script: |-
    [[ "${tag}" =~ ^[0-9]+(\.[0-9]+){2}$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Pcucumber-seeds -Psonar -Pqulice -Pintegration -Pcucumber -Psonatype --errors --settings ../settings.xml