language: java
jdk:
  - oraclejdk8
services:
  - docker
before_install:
  - docker pull vitorenesduarte/vcd
script:
  - make test
  - docker run -d -p 2181:2181 zookeeper
  - docker run -d -p 6000:6000 vitorenesduarte/vcd
  - make run
notifications:
  email: false
  slack: imdea-software:fdyPmym7oicfvSQTL5zy21n3
sudo: false
