# Run `travis lint` when changing this file to avoid breaking the build.


# Use a larger VM as we run a lot of services
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: required
dist: trusty

cache:
  directories:
  # zipkin-ui gets dependencies via NPM
  - $HOME/.npm
  - $HOME/.m2

language: java

jdk:
  - oraclejdk8

services:
  - docker
  - rabbitmq

before_install:
  # parameters used during a release
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "zipkinci"
  - git config user.email "zipkinci+zipkin-dev@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

  # Required for Elasticsearch 5 (See https://github.com/docker-library/docs/tree/master/elasticsearch#host-setup)
  - sudo sysctl -w vm.max_map_count=262144

  # Manually install and run zk+kafka as it isn't an available service
  - curl -SL http://archive.apache.org/dist/kafka/0.8.2.2/kafka_2.11-0.8.2.2.tgz | tar xz
  - nohup bash -c "cd kafka_* && bin/zookeeper-server-start.sh config/zookeeper.properties >/dev/null 2>&1 &"
  - nohup bash -c "cd kafka_* && bin/kafka-server-start.sh config/server.properties >/dev/null 2>&1 &"

  # Quiet Maven invoker logs (Downloading... when running zipkin-server/src/it)
  - echo "MAVEN_OPTS='-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'" > ~/.mavenrc

install:
  # Override default travis to use the maven wrapper
  # skip license on travis due to #1512
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dlicense.skip=true

script:
  - ./travis/publish.sh

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

env:
  global:
  # Ex. travis encrypt BINTRAY_USER=your_github_account
  - secure: "Ce34YTvUPNNmPaM98FWG9+QGI9aW9DBuWIvc5viCsNhlxGywWujlzvKFj2LVjdAp3ft8tpCd79ZHe3hMrfZ/SAzsT2qwNcAsUmE9YgjAFKyS7TS2CP2PMS+U7iFchCBZnCv7L6LUCClQa+pMBrSNNOJxDGK3woDxkf1FjgOY6hQ="
  # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: "gIWukQGUH6VoOldxuvYHaIeTGC4QBja5+ZUJPIhx5BlcXWweGwBlVeTTvBzdvYb3qcTjdr+tCDyonKuDsfxzxkPL7+aMK4f1Wxk8YyFouzrx/S2H9di3h4MptUk8S8JpAq7S5itWbb0fz0+R1qzCgDZR7ZBMpJWty2UIKho7zoo="
  # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
  - secure: "Wl88p48OjWFzNFHc6ilJxDYXwODlsOWRWUYqalMpJwR1znmPn2XrYrhBbfD+AMfDFHCWKGYjhqHj+/le5dF4m9+vM3PKD3wE3UJYXSMmcXqlK7A/ohcNiEuNvh84qP4XPtaVd+s8vJ4UdmeRQ0vUsIRASWqzdeTPn12YA5h6aDk="
  # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
  - secure: "EEIGkGWsje/NZmqEnS8Dhk92KAsFqq070hVCwEwUwUdRe4tZpL3eTOtSD8/Ul5ICtIApC08Mr4g+4sSkjztlCbkxycUSnUsfAJV3vTHyPnvdoztE1Yh6hm4UfTPbMNVFcigxMLOnApeaeB7x9CeRGPRbHuUONs44fuLPKDoYMo4="
  # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
  - secure: "hk1tiOe9D5ASlykwUbvSQlWR0Zz5FdFGhTxQSLZlVayypspaZm5igPJS8t9UfAlCgHc8WGrnUwybqzHUQzIRTd9etF9KXoUZcrinXh5Et0hd3V0OyMOpmgRdWinOqgE8oUXz2uZXTWbLu7uW365TUb4GKCdmK89iFnVXsCoR8wM="

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/637e968b45032d16ee26
    on_success: change
    on_failure: always
    on_start: false
