language: java
notifications:
  email: false
  irc:
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    channels:
    - chat.freenode.net#enmasse
    use_notice: true
    skip_join: true
sudo: required
services:
- docker
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
before_script:
- "./.travis/setup-kubernetes.sh"
before_install:
- npm install -g mocha mocha-junit-reporter
- npm install rhea debug
script:
- "./.travis/build.sh"
after_failure:
- "./.travis/upload-artifacts.sh false"
after_success:
- "./.travis/push.sh"
- "./.travis/upload-artifacts.sh true"
- "./.travis/trigger-docs.sh"
env:
  global:
  - BRANCH=${TRAVIS_BRANCH}
  - PULL_REQUEST=${TRAVIS_PULL_REQUEST}
  - TAG=${TRAVIS_TAG}
  - COMMIT=${TRAVIS_COMMIT::8}
  - DOCKER_ORG=enmasseproject
  - secure: UWNZ/UcF/mhS/QF6uen/LbeOM+Ohe1XNpfgwsf4H5RTiVg1R6UnLqoeYplRph2Ui11w27F6hkaNghpSzhPCMZX6H4OMtJ6EjXC16PblZYVYEM0Ee2eXT1HsQ4+48koH/VGCyqtI8Pg7DO/5gLjkAUImFymLpUh9lig00PcJ/ObNKvf/V5WU8LHwpxpPHpN+CJ9ZMGlgQ2BgrPCkD3Ht+0MqJgWCEN/3q6RRVp9fqS4NHePnhZB4ydd4eG1KAXMtoOiX2yCx+vRHw3/vaSau8fTsSBE/z2Z1LtzjIYYatPFqX6J13bW/aSwir3kZU3C2jN3UPcNRSl96A4wSAXX1IrVJ8DEnyf4fs1HVXx8XgzQjVwOnvylPlDbpxeAsRMAN6TQwa6fs9bXxfviQCoe9vFYcHHewc9uVF0GYx+K1/9kACsy2mLNwF38oLoMmhB/2IQIjYLzv2IElMy79vRd/bHb73VF0ZDcaTJW5SJiiam0HrdpmHZuRoExlmQYi8H9AQErLEB4wQRB3Xw0xaj+Ef5WWcZWFNCSJVC+xQyLcgrx6EGisJDM9e3a809EdCMya1GCITRw1lXlF5QbsTjyl8Q12ZIEFUcT4C90G9EUh56hz13OdBQTguChCUi+Nv819txdo+Pb0hFkxEM/d2dJFB3rcuWK6yeJ2vWKvH4I7odM4=
  - secure: d/t64DY8OY0yF6pjYtNmR6OEAHQ7QzR1qCR4LvIPuG/42pp/wVRltEBjUdAq9KMMBqvWPDj7QqNUhjZdAcnzWydSDyaa0mAs3l/nwsMtksQhbbBs3Kk5mBTRf9d238hSuGp+TBSZF8pCPhfM9tPTuZuJODVDiOhz2DPph4uF4wmh1q8yn4aaUsXZ71cJQcYgUZZHr1sNLhU0C/d9MizTDav0U9yqBaeYlwMBS/Dy3NIbZxp3bXu/agC2229aIL+Av8GS/7cT8tkTmtUyUyBEBXxFVxGNNPfnHF6dNRJSe0LV7j6xTEL1DivA2GKDdghiUo0ghnM9DVkmXr+ExNrlD+kMv+nxgySnVOVG1x1mgCGnuFDLQQ5pf5HTcgp82UO5z1eyon4vAvhLsCECovWYLZYB/dcYmg/kKPhv8hnIL+mssE9OgSrlNQYSAjRMnYicjoItXtt28eiibL3yp3gG+s8awN5Es9KQrLRTvC5dy6xXJRnQnhYfcwyRXAGsaRN/k1pNKDa1Yx4EwxAOpB+VNJUsTHX2yhBDmt6ZGDtOpAAf6YhLFd/0Uitq3icannOyrZzTeZR/Gv9DnS9A3+BFB68cPgHUH2vfO2fE2cNqCRt6pt9KWxTTKrCvTnVyQn25NVqxNyRum3eps321N57JmPTglZGj0I1DvC9m8iNWwNU=
  - secure: TY6XV1K2zRxpCy64V9tOSt9gTXvhJEX6ZTtxFG8wid5n/V+ubwF5J79mgvEO4NIS98Jr/rOHFqUO2gwlFg0NvpAMoDjdF5rXqznAlPtYSW7xNsBRN0Ry6epHKZZ6xa8EIfdeqgciYD1tjUZXjq0ZOh3hV1GZ15rOr/AYlzrMRwKP7uMluaTZjIgCMLbNFXlzPNVChtfY8mR+cP4SrZXPlhbxmGjI6MksKtHjdz6EN+5avz9TdjxPlOC29ePddyF/QuhArDHop0hAavcDiAYe9BCaMthkiXKeDGIOVFZNetbv0WsdtVSiDu4cDElT7vNLwypwN6QAAFuNZlHDbYfNFd8F6uoj1IDFNMxquP0vOn0Jdd1/HFT2uW94CIRFv+r2oAsNCBd6A1Kfdk8uGuKqBHja5InNtGN5Iw9r5pNDtcUgUZKOZ7O4R50OwC7XVi11xgCzihiyMRX2ogdIKgGkbVwh63fiKsvKUv/2IDRpcw0klVPCz+sRIkaRfxCxVAcYQf93McXfbN/eWjH1qgM7WHpLazk2hi1mmHw7mWvS3MAZ9zNXDNurQw1qXHmecfcxkKG/vu1NQNbGZUoViiG+LKOv7XtWpjxHrvrw2ejt8wYWC51Zv/Jxo4qAZEckZLj9XBCgvONaefBru7LX9VHENGMPP0fxEzI+lJZLQUmUC0g=
  - secure: WF0i7xDmu6WQnnijAuRj0QqsLK+lWhdL0tolR3Yn+GyZGJmkZq/jzpzZWcE/uJe5YRwXolwS1cxuPFY/wGl5PPQN6blSp2MJVGVfBx92x/Vleqw4XkQbWXhDUIyGP5Uc/Yx7jO19a93LjbVcpZOzR6/nnChZfNCLm1CHM5KCS/rV3KHF6T14V2u+x2G6Lg264qVvmtOeGr/IrBVjWiXj+9aEvY+hzw2dvTe6Wk6KBjGe8DMDjdWI1mxtRuqFlW69YLOYBcEKj6h2s7dT9ZeS7Z6+n9Zj+OfJpURxlr/+K64csdpHqajiR0hswSVlDJANmNBdMm5b1eIelbTfrCwdEqLNKgUr7+ihjlKWOEerI2Jrpeu4Sxt2EWrFeJNklsqJve0N6+ZS47MDWiTGB2oWadtUbXc+Uko84vrYbS4anOtvR8JX14dGuZl0l0Wdl7uIxhM0dg14bBYhea/R3d38CrJ43+672UQ5WLYeKn31UeAFFdSpAhRqE+j94Ue3GpQrRA6phadMYpxJCQ8yfRrLAcTchRpD9IE+QwBGehR8AZ4CU63iXq+lrlZjAfRLHw0j7XSxfgoyVm/UGqfmg95EhYER8d8RurNY9ctXVRYaJOC9jlRVZWhPULtVK1+jklbi+8kw8ZUeuoj2ggplxAYCZjFwPCwNqhyqP43IfsdpYio=
  - secure: jZacd85V6d2N/8NM5YjnbCtGuyeYRj5avzQjlKmVskIon9WdKr2/QhAOJc2UxGPLR2WVT3m2+JxmjidlL25FnA3PKGb8hRCCpBmIBFq2VwKhT8U1sEr1DfV3zZlQyxbp7tkiMKJ2cj+3aLBbmGieRr6AshDEMmXuXNN3k3tVCMns/G+pW7Pz82jQwJqmiOpdp4DgyiRXVQEPDxf5XJT4jYt1/KjMx8N6Vob5TqraGYPHTKQiufIebhS+MfFxo0Kpc7izYoBVNC547N8VY4Ra0A0hRyatx/hNiN5QzYHIds2TUHuy3Bin3KJ88qy7Q0zWUNndNg+sNc6FKkyqSw+alDq/cTOje5xpTFnatvS0f4gj42vsHceFhwrIj6O0CbUilWpVYY7wTO+G5JHXop/Q9T74UpJax6mrft++vlr7ahBk5kT+7I4Sph1X4eKWHFkzORfiS8Y8D9mLNGFXnW3OrvZNPdehBvEvshxBkTKVyZyP4DfIQKLfdzn29GQeYhZFipypR88jS5mqG7BZhEQuWjstiOBOi+8yo8B47uMpLPLhKjYgZuirJXem0GS959EqqygQApnLqHqoz+v0027wze4OBc8WmhAmRNRAaXluzsBar7aGWe7Sd6scn7nLl+YVTLkXtNDkoFWQVksr+5f/HUbcYilabAFLtPhLL8Hq35M=
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: HepZcALZznJ9XL1gumw4EqtG2doiWX+dEdUy0Qug+DcFM6mTb7m61YIrYmiw0h2FCqzozsSjlDjKfBLUgnUalj6f6LZCQKqThh04VKQoBmDJbUoOX7nSiaGeV9SJ18zeG8MrIkoHriJVGnfKUTL870RSQGzRvCXOUyQdx9gy/kfFFM4R9eUN8XOH/nMdmMhtoqwlhfjcY8T0qeKlCISqFCXlan+uIV7KERVSiiBdK4L4fsA5VB8Dd3SUHKe2zpcntowsBXfGI9wemWe++FysZ4Wsg+bBohiZ11A2xeHWCpswosvUHl8OcRyQDK5RqLsphdhTcFxaKvuyXl8v0eecg4ktdHkVQ0EbEauTtd/19lDa4oNpv/Thm3ElKpM77xq4gf0CLW/QNCO6OSQ9zPKughyaH3b/lseLWvVxYEKsPanRdYCZO0PjVOUGtbUpPRxP5CkNDEkW7mpfbK0IgxAemGy0mcTnSWFKQOgdB9iyiZA+lrHdrF9pc1rj5QPbDE8e7mn7FoosPsZuwGjZAb/7lBdZ4aerUXHHsBoyRrVEMvj1qABv9UJtokgo3rBoY/JGdHX9Rq9gsVVQeLLFir5EIFlsTXoaj4z+NvwC5ODklNdBoQvkXYzZ6z9OYsCGDjl09rFi7AbMXCM7nLeKzUv3XQbuEr9iHHpkWhKO8gc8hNw=
  file: templates/build/enmasse-${TRAVIS_TAG}.tgz
  on:
    tags: true
    repo: EnMasseProject/enmasse
