# configuration for https://travis-ci.org/cpesch/RouteConverter
sudo: false
language: java
cache:
 directories:
   - $HOME/.m2
jdk:
  - openjdk7
  - oraclejdk8
  - oraclejdk9
git:
  depth: 3
branches:
  only:
    - master
notifications:
  email:
  - support@routeconverter.com