---
# tasks file for install npm, pip etc...
- name: check to see if pip is already installed
  command: "pip --version"
  ignore_errors: true
  register: pip_is_installed
  changed_when: false

- name: download get-pip.py
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp
  when: pip_is_installed.rc != 0

- name: install pip
  command: "python /tmp/get-pip.py"
  when: pip_is_installed.rc != 0

- name: delete get-pip.py
  file:
    state: absent
    path: /tmp/get-pip.py
  when: pip_is_installed.rc != 0

- name: Install redhat-rpm-config
  yum:
    name: redhat-rpm-config
    state: present

- name: Install python-devel
  yum:
    name: python-devel
    state: present

- name: Install openssl
  yum:
    name: openssl
    state: latest

- name: Install openssl-devel
  yum:
    name: openssl-devel
    state: latest

- include_tasks: epel.yml

- name: Install nodejs
  yum:
    name: "nodejs-{{ nodejs_version }}.*"
    state: present
    enablerepo: epel

- name: install the Xvfb
  yum:
    name: xorg-x11-server-Xvfb
    state: latest

- name: install the firefox
  yum:
    name: firefox
    state: latest

- name: Chceck if maven is present
  command: "mvn --version || cd {{ maven_path }}"
  ignore_errors: true
  register: mvn_is_installed
  changed_when: false

- name: Download apache maven
  get_url:
    url: https://archive.apache.org/dist/maven/maven-3/3.5.2/binaries/apache-maven-3.5.2-bin.tar.gz
    dest: "{{ maven_root_path }}"
  when: mvn_is_installed.rc != 0

- name: Extract apache maven
  unarchive:
    src: "{{ maven_root_path }}/apache-maven-3.5.2-bin.tar.gz"
    dest: "{{ maven_root_path }}"
  when: mvn_is_installed.rc != 0

