apiVersion: v1
kind: ConfigMap
metadata:
  name: small-queue-plan
  labels:
    type: address-plan
data:
  definition: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "AddressPlan",
      "metadata": {
        "name": "small-queue"
      },
      "displayName": "Small queue plan",
      "displayOrder": 0,
      "shortDescription": "A plan for small queues",
      "longDescription": "A plan for small queues that consume little resources",
      "uuid": "98feabb6-1183-11e8-a769-507b9def37d9",
      "addressType": "queue",
      "requiredResources": [
        {
          "name": "router",
          "credit": 0.2
        },
        {
          "name": "broker",
          "credit": 0.3
        }
      ]
    }
