version: '2'
services:
  activiti-cloud-registry:
    image: activiti/activiti-cloud-registry:latest
    ports:
     - "8761:8761"
    environment:
      - JAVA_OPTS=-Xmx64m -Xms64m
      - ACT_CLOUD_CONFIG_SERVER_ENABLED=false
      - SPRING_PROFILES_ACTIVE=git
    volumes:
      - "/tmp/config-repo:/tmp/config-repo"
  activiti-cloud-gateway:
    image: activiti/activiti-cloud-gateway:latest
    depends_on:
     - activiti-cloud-registry
    ports:
     - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx64m -Xms64m
      # - ACT_KEYCLOAK_CORS=false
  activiti-cloud-audit:
      image: activiti/activiti-cloud-audit:latest
      external_links:
        - activiti-cloud-sso-idm
        - activiti-cloud-registry
        - rabbitmq
      environment:
        - SPRING_APPLICATION_NAME=activiti-cloud-audit
        - ACT_AUDIT_PORT=8181
        - JAVA_OPTS=-Xmx128m -Xms128m
        - ACT_CLOUD_CONFIG_SERVER_ENABLED=false
  rb-postgres:
    image: postgres
    ports:
     - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=activitidb
  # We define the name and the base image of our Runtime Bundle
  rb-my-app:
      # Set image: to whichever you are using
      # This image was generated by the docker-runtime-bundle/Dockerfile
      image: activiti/example-runtime-bundle:latest
      # This image was generated by the maven-runtime-bundle project
      #image: rb-my-maven-app
      external_links:
        - activiti-cloud-sso-idm
        - activiti-cloud-registry
        - rabbitmq
      depends_on:
        - rb-postgres
      # You can launch as many Runtime Bundles as you want by changing these Env variables
      environment:
        - ACT_RB_PORT=8081
        - ACT_RB_HOST=rb-my-app
        - ACT_RB_APP_NAME=rb-my-app
        - ACT_RB_DB_URI=jdbc:postgresql://rb-postgres:5432/activitidb
        - ACT_RB_DB_USER=postgres
        - ACT_RB_DB_PASS=password
        - ACT_RB_DB_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
        - JAVA_OPTS=-Xmx256m -Xms256m
        - ACT_CLOUD_CONFIG_SERVER_ENABLED=false
        - SPRING_HATEOAS_USEHALASDEFAULTJSONMEDIATYPE=false
  activiti-cloud-query:
    image: activiti/activiti-cloud-query:latest
    ports:
      - 8182:8182
    external_links:
      - activiti-cloud-sso-idm
      - activiti-cloud-registry
      - rabbitmq
    environment:
      - SPRING_APPLICATION_NAME=activiti-cloud-query
      - ACT_QUERY_PORT=8182
      - JAVA_OPTS=-Xmx128m -Xms128m
      - ACT_CLOUD_CONFIG_SERVER_ENABLED=false
      - ACT_QUERY_DB_URI=jdbc:postgresql://rb-postgres:5432/activitidb
      - ACT_QUERY_DB_USER=postgres
      - ACT_QUERY_DB_PASS=password
      - ACT_QUERY_DB_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_ACTIVITI_CLOUD_SERVICES_NOTIFICATIONS_GATEWAY_ENABLED=false
      - SPRING_ACTIVITI_CLOUD_SERVICES_QUERY_GRAPHQL_ENABLED=false
      - SPRING_HATEOAS_USEHALASDEFAULTJSONMEDIATYPE=false
