apiVersion: v1
kind: ConfigMap
metadata:
  name: address-space-plan-standard
  labels:
    type: address-space-plan
data:
  definition: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "AddressSpacePlan",
      "metadata": {
        "name": "unlimited-standard",
        "annotations": {
          "enmasse.io/defined-by": "standard-space"
        }
      },
      "displayName": "Unlimited",
      "displayOrder": 0,
      "shortDescription": "Unlimited plan without resource restrictions.",
      "longDescription": "Unlimited plan where you can create an large number of addresses until the system (probably) falls over.",
      "uuid": "f084d7f4-0501-11e8-a572-507b9def37d9",
      "addressSpaceType": "standard",
      "resources": [
        {
          "name": "router",
          "min": 1.0,
          "max": 10000.0
        },
        {
          "name": "broker",
          "min": 1.0,
          "max": 10000.0
        },
        {
          "name": "aggregate",
          "min": 1.0,
          "max": 10000.0
        }
      ],
      "addressPlans": [
        "standard-anycast",
        "standard-multicast",
        "sharded-queue",
        "pooled-queue",
        "sharded-topic",
        "pooled-topic"
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: address-space-plan-standard-mqtt
  labels:
    type: address-space-plan
data:
  definition: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "AddressSpacePlan",
      "metadata": {
        "name": "unlimited-standard-without-mqtt",
        "annotations": {
          "enmasse.io/defined-by": "standard-space-without-mqtt"
        }
      },
      "displayName": "Unlimited",
      "displayOrder": 0,
      "shortDescription": "Unlimited plan without resource restrictions.",
      "longDescription": "Unlimited plan where you can create an large number of addresses until the system (probably) falls over.",
      "uuid": "f084d7f4-0501-11e8-a572-507b9def37d9",
      "addressSpaceType": "standard",
      "resources": [
        {
          "name": "router",
          "min": 1.0,
          "max": 10000.0
        },
        {
          "name": "broker",
          "min": 1.0,
          "max": 10000.0
        },
        {
          "name": "aggregate",
          "min": 1.0,
          "max": 10000.0
        }
      ],
      "addressPlans": [
        "standard-anycast",
        "standard-multicast",
        "sharded-queue",
        "pooled-queue",
        "sharded-topic",
        "pooled-topic"
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-definition-standard
  labels:
    type: resource-definition
data:
  definition: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "ResourceDefinition",
      "metadata": {
        "name": "standard-space"
      },
      "template": "standard-space-infra"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resource-definition-standard-mqtt
  labels:
    type: resource-definition
data:
  definition: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "ResourceDefinition",
      "metadata": {
        "name": "standard-space-without-mqtt"
      },
      "template": "standard-space-infra-without-mqtt"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: address-plan-sharded-queue
  labels:
    type: address-plan
data:
  definition: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "AddressPlan",
      "metadata": {
        "name": "sharded-queue"
      },
      "displayName": "Sharded Queue",
      "displayOrder": 0,
      "shortDescription": "Creates a queue on a standalone broker.",
      "longDescription": "Creates a queue on a standalone broker that can be sharded.",
      "uuid": "aeddd606-0502-11e8-ad75-507b9def37d9",
      "addressType": "queue",
      "requiredResources": [
        {
          "name": "router",
          "credit": 0.01
        },
        {
          "name": "broker",
          "credit": 1.0
        }
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: address-plan-pooled-queue
  labels:
    type: address-plan
data:
  definition: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "AddressPlan",
      "metadata": {
        "name": "pooled-queue"
      },
      "displayName": "Pooled Queue",
      "displayOrder": 0,
      "shortDescription": "Creates a queue on a pooled broker.",
      "longDescription": "Creates a queue on a pooled broker shared with other queues.",
      "uuid": "0843743a-0503-11e8-91df-507b9def37d9",
      "addressType": "queue",
      "requiredResources": [
        {
          "name": "router",
          "credit": 0.01
        },
        {
          "name": "broker",
          "credit": 0.01
        }
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: address-plan-standard-anycast
  labels:
    type: address-plan
data:
  definition: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "AddressPlan",
      "metadata": {
        "name": "standard-anycast"
      },
      "displayName": "Standard",
      "displayOrder": 0,
      "shortDescription": "Creates a direct anycast address.",
      "longDescription": "Creates a direct anycast address where messages go via a router that does not take ownership of the messages.",
      "uuid": "45edd942-0503-11e8-84ce-507b9def37d9",
      "addressType": "anycast",
      "requiredResources": [
        {
          "name": "router",
          "credit": 0.01
        }
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: address-plan-standard-multicast
  labels:
    type: address-plan
data:
  definition: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "AddressPlan",
      "metadata": {
        "name": "standard-multicast"
      },
      "displayName": "Standard",
      "displayOrder": 0,
      "shortDescription": "Creates a direct multicast address.",
      "longDescription": "Creates a direct multicast address where messages go via a router that does not take ownership of the messages.",
      "uuid": "60fc2702-0503-11e8-b60e-507b9def37d9",
      "addressType": "multicast",
      "requiredResources": [
        {
          "name": "router",
          "credit": 0.01
        }
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: address-plan-sharded-topic
  labels:
    type: address-plan
data:
  definition: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "AddressPlan",
      "metadata": {
        "name": "sharded-topic"
      },
      "displayName": "Sharded Topic",
      "displayOrder": 0,
      "shortDescription": "Creates a topic on a standalone broker.",
      "longDescription": "Creates a topic on a standalone broker that can be sharded.",
      "uuid": "de256d34-0502-11e8-98c9-507b9def37d9",
      "addressType": "topic",
      "requiredResources": [
        {
          "name": "router",
          "credit": 0.01
        },
        {
          "name": "broker",
          "credit": 1.0
        }
      ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: address-plan-pooled-topic
  labels:
    type: address-plan
data:
  definition: |-
    {
      "apiVersion": "enmasse.io/v1",
      "kind": "AddressPlan",
      "metadata": {
        "name": "pooled-topic"
      },
      "displayName": "Pooled Topic",
      "displayOrder": 0,
      "shortDescription": "Creates a topic on a shared broker.",
      "longDescription": "Creates a topic on a shared broker with other topics.",
      "uuid": "45e0bc24-155e-11e8-8962-507b9def37d9",
      "addressType": "topic",
      "requiredResources": [
        {
          "name": "router",
          "credit": 0.01
        },
        {
          "name": "broker",
          "credit": 0.01
        }
      ]
    }
