transform.source.names=source1,source2

source1.transform.input.schema=/hdfs/path/to/source1/input/schema/schema.avsc
source2.transform.input.schema=/hdfs/path/to/source2/input/schema/schema.avsc
transform.output.schema=/hdfs/path/to/output/schema/schema.avsc

source1.transform.input.path=/hdfs/path/to/source1/avro/input/
source2.transform.input.path=/hdfs/path/to/source2/avro/input/
transform.output.path=/hdfs/path/to/output/

transform.udf.class=com.linkedin.thirdeye.hadoop.transform.DefaultTransformUDF
transform.config.udf.class=com.linkedin.thirdeye.hadoop.transform.DefaultTransformConfigUDF

transform.num.reducers=10