join.output.schema=/hdfs/path/to/output/schema/schema.avsc
join.output.path=/hdfs/path/to/output

join.config.udf.class=com.linkedin.thirdeye.hadoop.join.DefaultJoinConfigUDF
join.key.extractor.class=com.linkedin.thirdeye.hadoop.join.DefaultJoinKeyExtractor
join.udf.class=com.linkedin.thirdeye.hadoop.join.GenericJoinUDF

join.source.names=source1,source2
source1.join.input.schema=/hdfs/path/to/source1/schema/schema.avsc
source2.join.input.schema=/hdfs/path/to/source2/schema/schema.avsc
source1.join.input.path=/hdfs/path/to/source1/avro/input/
source2.join.input.path=/hdfs/path/to/source2/avro/input/