apiVersion: v1
kind: Template
objects:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: enmasse
    name: none-authservice
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: enmasse
          name: none-authservice
      spec:
        containers:
        - env:
          - name: LISTENPORT
            value: '5671'
          image: ${NONE_AUTHSERVICE_IMAGE}
          livenessProbe:
            initialDelaySeconds: 60
            tcpSocket:
              port: amqps
          name: none-authservice
          ports:
          - containerPort: 5671
            name: amqps
          resources:
            limits:
              memory: 48Mi
            requests:
              memory: 48Mi
          volumeMounts:
          - mountPath: /opt/none-authservice/cert
            name: ${NONE_AUTHSERVICE_CERT_SECRET_NAME}
            readOnly: false
        volumes:
        - name: ${NONE_AUTHSERVICE_CERT_SECRET_NAME}
          secret:
            secretName: ${NONE_AUTHSERVICE_CERT_SECRET_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: enmasse
    name: none-authservice
  spec:
    ports:
    - name: amqps
      port: 5671
      protocol: TCP
      targetPort: amqps
    selector:
      name: none-authservice
parameters:
- description: The docker image to use for the 'none' auth service
  name: NONE_AUTHSERVICE_IMAGE
  value: docker.io/enmasseproject/none-authservice:latest
- description: The secret to use for the none-authservice certificate
  name: NONE_AUTHSERVICE_CERT_SECRET_NAME
  value: none-authservice-cert
