- name: Check if keycloak credentials secret exists
  shell: oc get secret -n {{ namespace }} keycloak-credentials
  register: secret_exists
  ignore_errors: True
- name: Create secret with the keycloak credentials
  when: secret_exists.failed
  shell: oc create secret generic -n {{ namespace }} keycloak-credentials --from-literal=admin.username=admin --from-literal=admin.password={{ keycloak_admin_password }}
- name: Give view permissions for the keycloak controller
  shell: oc adm policy add-role-to-user view system:serviceaccount:{{ namespace }}:default
- name: Create the standard authentication service
  shell: oc process -f {{ playbook_dir }}/templates/addons/standard-authservice.yaml | oc apply -n {{ namespace }} -f -
